import webpush from "web-push";
import { DurableObject } from "cloudflare:workers";
export class ReminderDevice extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.db=ctx.storage.sql;this.db.exec("CREATE TABLE IF NOT EXISTS subscriptions (id INTEGER PRIMARY KEY, subscription_json TEXT NOT NULL)");this.db.exec("CREATE TABLE IF NOT EXISTS reminders (id TEXT PRIMARY KEY, fire_at INTEGER NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, tag TEXT, url TEXT, repeat_ms INTEGER DEFAULT 0)")}
 async subscribe(s){this.db.exec("INSERT INTO subscriptions(id,subscription_json) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET subscription_json=excluded.subscription_json",JSON.stringify(s));return{ok:true}}
 async schedule(r){if(!Number.isFinite(r.fireAt)||r.fireAt<=Date.now())return{ok:false,error:"Invalid future time"};this.db.exec("INSERT INTO reminders(id,fire_at,title,body,tag,url,repeat_ms) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET fire_at=excluded.fire_at,title=excluded.title,body=excluded.body,tag=excluded.tag,url=excluded.url,repeat_ms=excluded.repeat_ms",r.id,r.fireAt,r.title,r.body,r.tag||"ittime",r.url||"/",Number(r.repeatMs)||0);await this.arm();return{ok:true}}
 async cancel(id){this.db.exec("DELETE FROM reminders WHERE id=?",id);await this.arm();return{ok:true}}
 async test(){const row=[...this.db.exec("SELECT subscription_json FROM subscriptions WHERE id=1")][0];if(!row)return{ok:false,error:"No push subscription is registered for this device."};const sub=JSON.parse(row.subscription_json);webpush.setVapidDetails(this.env.VAPID_SUBJECT,this.env.VAPID_PUBLIC_KEY,this.env.VAPID_PRIVATE_KEY);try{await webpush.sendNotification(sub,JSON.stringify({title:"ItTime — Test Notification",body:"Reliable push notifications are working.",tag:"ittime-test",url:"/"}));return{ok:true}}catch(e){if(e?.statusCode===404||e?.statusCode===410)this.db.exec("DELETE FROM subscriptions WHERE id=1");return{ok:false,error:"Push delivery failed: "+(e?.message||e)}}}
 async arm(){const a=[...this.db.exec("SELECT fire_at FROM reminders ORDER BY fire_at ASC LIMIT 1")];if(a.length)await this.ctx.storage.setAlarm(Math.max(Date.now()+1000,Number(a[0].fire_at)));else await this.ctx.storage.deleteAlarm()}
 async alarm(){const now=Date.now(),due=[...this.db.exec("SELECT id,title,body,tag,url,repeat_ms FROM reminders WHERE fire_at<=? ORDER BY fire_at ASC LIMIT 20",now)],row=[...this.db.exec("SELECT subscription_json FROM subscriptions WHERE id=1")][0];if(row){const sub=JSON.parse(row.subscription_json);webpush.setVapidDetails(this.env.VAPID_SUBJECT,this.env.VAPID_PUBLIC_KEY,this.env.VAPID_PRIVATE_KEY);for(const r of due){try{await webpush.sendNotification(sub,JSON.stringify({title:r.title,body:r.body,tag:r.tag||"ittime",url:r.url||"/"}))}catch(e){if(e?.statusCode===404||e?.statusCode===410)this.db.exec("DELETE FROM subscriptions WHERE id=1")}if(Number(r.repeat_ms)>0)this.db.exec("UPDATE reminders SET fire_at=? WHERE id=?",now+Number(r.repeat_ms),r.id);else this.db.exec("DELETE FROM reminders WHERE id=?",r.id)}}else for(const r of due)this.db.exec("DELETE FROM reminders WHERE id=?",r.id);await this.arm()}}
function json(d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"Content-Type, Authorization","access-control-allow-methods":"GET,POST,OPTIONS"}})}
function auth(r,e){return!!e.API_TOKEN&&r.headers.get("Authorization")===`Bearer ${e.API_TOKEN}`}
export default{async fetch(request,env){if(request.method==="OPTIONS")return json({ok:true});const u=new URL(request.url);if(u.pathname==="/health")return json({ok:true,service:"ItTime Push"});if(u.pathname==="/vapid-public-key"&&request.method==="GET")return json({publicKey:env.VAPID_PUBLIC_KEY});if(!auth(request,env))return json({error:"Unauthorized"},401);let b={};try{b=await request.json()}catch{return json({error:"Invalid JSON"},400)}if(!b.deviceId)return json({error:"deviceId required"},400);const stub=env.REMINDER_DO.get(env.REMINDER_DO.idFromName(String(b.deviceId)));if(u.pathname==="/subscribe"&&request.method==="POST"){if(!b.subscription?.endpoint||!b.subscription?.keys)return json({error:"Invalid subscription"},400);return json(await stub.subscribe(b.subscription))}if(u.pathname==="/schedule"&&request.method==="POST"){if(!b.reminderId||!b.title||!b.body||!Number.isFinite(b.fireAt))return json({error:"Missing reminder fields"},400);return json(await stub.schedule(b))}if(u.pathname==="/cancel"&&request.method==="POST"){if(!b.reminderId)return json({error:"reminderId required"},400);return json(await stub.cancel(String(b.reminderId)))}if(u.pathname==="/test"&&request.method==="POST")return json(await stub.test());return json({error:"Not found"},404)}};
